server:
  port: 8000

spring:
  application:
    name: product
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.255.129:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: bubbleboy001
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.129:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
logging:
  level:
    org.apache.ibatis: debug





